# Generated by Django 4.0.4 on 2022-05-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface_play', '0002_rename_paramnames_surfacerecord_parameter_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfacerecord',
            name='u_max',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='surfacerecord',
            name='u_min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='surfacerecord',
            name='v_max',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='surfacerecord',
            name='v_min',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='surfacerecord',
            name='X',
            field=models.CharField(default='u', max_length=400),
        ),
        migrations.AlterField(
            model_name='surfacerecord',
            name='Y',
            field=models.CharField(default='v', max_length=400),
        ),
        migrations.AlterField(
            model_name='surfacerecord',
            name='Z',
            field=models.CharField(default='u*u+v*v', max_length=400),
        ),
        migrations.AlterField(
            model_name='surfacerecord',
            name='parameter_names',
            field=models.CharField(default='u v', max_length=30),
        ),
    ]
