# Generated by Django 4.0.4 on 2022-06-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface_play', '0003_surfacerecord_u_max_surfacerecord_u_min_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surfacerecord',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='surfacerecord',
            name='Z',
            field=models.CharField(default='0', max_length=400),
        ),
    ]
