# Generated by Django 4.0.4 on 2026-03-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface_play', '0004_alter_surfacerecord_options_alter_surfacerecord_z'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfacerecord',
            name='thumbnail',
            field=models.TextField(blank=True, default=''),
        ),
    ]
