# Generated by Django 4.2.30 on 2026-05-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface_play', '0008_surfacerecord_initial_perspective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfacerecord',
            name='X',
            field=models.TextField(default='u'),
        ),
        migrations.AlterField(
            model_name='surfacerecord',
            name='Y',
            field=models.TextField(default='v'),
        ),
        migrations.AlterField(
            model_name='surfacerecord',
            name='Z',
            field=models.TextField(default='0'),
        ),
    ]
