# Generated by Django 4.2.30 on 2026-05-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface_play', '0009_alter_surfacerecord_x_alter_surfacerecord_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfacerecord',
            name='boundary_identify',
            field=models.CharField(choices=[('an', 'Antipodal'), ('no', 'None')], default='no', max_length=2),
        ),
    ]
